services:
  hr-monitor-backend:
    build:
      context: ./hr-monitor-backend
    ports:
      - "8000:8000"
    environment:
      - KAFKA_BROKER=${KAFKA_BROKER}

  hr-monitor-frontend:
    image: nginx:alpine
    volumes:
      - ./hr-monitor-frontend:/usr/share/nginx/html:ro
    ports:
      - "5000:80"
