version: '3.8'

services:
  hr-monitor-backend:
    build:
      context: ./hr-monitor-backend
    ports:
      - "8000:8000"
    environment:
      - KAFKA_BROKER=${KAFKA_BROKER}
    networks:
      - kafka-net

  hr-monitor-frontend:
    image: nginx:alpine
    volumes:
      - ./hr-monitor-frontend:/usr/share/nginx/html:ro
    ports:
      - "5000:80"
    networks:
      - kafka-net

networks:
  kafka-net:
    external: true
